-- liquibase formatted sql

-- changeset evgeniyth:1
CREATE TABLE "ROLES"
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

-- changeset evgeniyth:2
INSERT INTO "ROLES" (name) VALUES ('ROLE_USER');
INSERT INTO "ROLES" (name) VALUES ('ROLE_ADMIN');

-- changeset evgeniyth:3
CREATE TABLE "USERS"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR NOT NULL,
    last_name   VARCHAR NOT NULL,
    username    VARCHAR NOT NULL UNIQUE,
    password    VARCHAR NOT NULL,
    email       VARCHAR NOT NULL UNIQUE,
    phone       VARCHAR NOT NULL UNIQUE,
    avatar_path VARCHAR
);

-- changeset evgeniyth:4
CREATE TABLE "ADS"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR          NOT NULL,
    description VARCHAR          NOT NULL,
    price       DOUBLE PRECISION NOT NULL,
    image_path  VARCHAR,
    user_id     BIGINT           NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "USERS" (id)
);

-- changeset evgeniyth:5
CREATE TABLE "COMMENTS"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text          VARCHAR NOT NULL,
    creation_time BIGINT  NOT NULL,
    ad_id         BIGINT  NOT NULL,
    FOREIGN KEY (ad_id) REFERENCES "ADS" (id)
);

-- changeset evgeniyth:6
CREATE TABLE "USERS_ROLES"
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES "USERS" (id),
    FOREIGN KEY (role_id) REFERENCES "ROLES" (id)
);
